### ISSUE TITLE
Hardcoded Username and password

### ISSUE THREAD

**Issue by develhopper** [mahs4d/tsetmc-webservice#1]
سلام یک یوزر و پسورد توی  یکی از فایل ها [لینک](https://github.com/mahs4d/tsetmc-webservice/blob/master/.ipynb_checkpoints/Untitled-checkpoint.ipynb) در خط 21 هاردکد شده
گفتم گزارش بدم شاید مهم باشه

**Comment by mahs4d** [comment]
ممنونم ازتون 🙏🙏
یوزر پسورد از هیستوری حذف شدند
